# Generated by Django 5.0.4 on 2024-04-20 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Наименование категории', max_length=100, verbose_name='Наименование категории')),
                ('category_description', models.TextField(blank=True, help_text='Сделайте описание категории', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Наименование продукта', max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, help_text='Описание продукта', null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='products/', verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Цена за покупку')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания (в БД)')),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Введите категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producns', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ['product_name', 'category'],
            },
        ),
    ]
