# Generated by Django 5.0.4 on 2024-05-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_category_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_version",
                    models.IntegerField(default=1, verbose_name="номер версии"),
                ),
                (
                    "name_version",
                    models.CharField(max_length=150, verbose_name="имя версии"),
                ),
                (
                    "version_flag",
                    models.BooleanField(default=False, verbose_name="признак версии"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version",
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "версия продукта",
                "verbose_name_plural": "версии продуктов",
            },
        ),
    ]
