# Generated by Django 5.0.4 on 2024-04-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_product_manufactured_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="catalog/",
                verbose_name="Изображение",
            ),
        ),
    ]
