# Generated by Django 5.0.4 on 2024-04-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Цена за покупку"
            ),
        ),
    ]
